### ISSUE TITLE
Grant of a special permission - necessary or not?

### ISSUE THREAD

**Issue by AngelaIp** [AngelaIp/cui-select-starting-page#2]
The Method BPL_SelectStartingPage_onClick seems to work for every user without any grant of a special permission. But from my understanding only admins users have the right to edit User properties.

Did I miss something here?

**Comment by cgillis-aras** [comment]
If you look at the permissions of the Preference ItemType, you'll see that the "Creator" of a Preference is allowed to edit it. Preferences are typically created automatically whenever a user logs in for the first time, and each user is marked as the creator of their own corresponding preference. Because of this you don't need any special permissions.

**Comment by AngelaIp** [comment]
Thanks for the explanation! That makes sense and I'm glad that I do not need any extra permission handling.
